<?php

namespace App\Enums;

// docs/11 §30a — append-only authentication and security events. Names only:
// nothing records them yet (the recorder arrives with PWA-1D).
enum AuthSecurityEventType: string
{
    case ACTIVATION_REQUESTED = 'ACTIVATION_REQUESTED';
    case ACTIVATION_COMPLETED = 'ACTIVATION_COMPLETED';
    case OTP_ISSUED = 'OTP_ISSUED';
    case OTP_FAILED = 'OTP_FAILED';
    case OTP_LOCKED = 'OTP_LOCKED';
    // The correct code was entered: the grant window is open (PWA-1E).
    case OTP_VERIFIED = 'OTP_VERIFIED';
    case OTP_CONSUMED = 'OTP_CONSUMED';
    case LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED';
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case MOBILE_TRUST_OPENED = 'MOBILE_TRUST_OPENED';
    case MOBILE_TRUST_ASSISTED = 'MOBILE_TRUST_ASSISTED';
    case MOBILE_TRUST_GRANTED = 'MOBILE_TRUST_GRANTED';
    case MOBILE_TRUST_STALE = 'MOBILE_TRUST_STALE';
    case MOBILE_TRUST_REVOKED = 'MOBILE_TRUST_REVOKED';
    case LINK_ACTIVATED = 'LINK_ACTIVATED';
    case LINK_SUSPENDED = 'LINK_SUSPENDED';
    case LINK_RESUMED = 'LINK_RESUMED';
    case LINK_ENDED = 'LINK_ENDED';
    case LOGIN_IDENTIFIER_ROTATED = 'LOGIN_IDENTIFIER_ROTATED';
    case IDENTITY_MISMATCH = 'IDENTITY_MISMATCH';
    case AMBIGUOUS_IDENTITY = 'AMBIGUOUS_IDENTITY';
    case ELIGIBILITY_DENIED = 'ELIGIBILITY_DENIED';
    case SESSIONS_REVOKED = 'SESSIONS_REVOKED';
    case COORDINATOR_SCOPE_ASSIGNED = 'COORDINATOR_SCOPE_ASSIGNED';
    case COORDINATOR_SCOPE_REVOKED = 'COORDINATOR_SCOPE_REVOKED';
    // The COORDINATOR role itself (PWA-1H); the scopes are recorded above.
    case COORDINATOR_ROLE_GRANTED = 'COORDINATOR_ROLE_GRANTED';
    case COORDINATOR_ROLE_REVOKED = 'COORDINATOR_ROLE_REVOKED';
    // The household head revealed one of their OWN sensitive values
    // (PWA-3B.2); metadata: the field code only, never the value.
    case SELF_SENSITIVE_REVEALED = 'SELF_SENSITIVE_REVEALED';
}
